---
type: lightning   # por sugestão da Bea Milz
language: portuguese
year: '`r format(Sys.Date(), "%Y")`' 
title: "A Comunidade `R Brasil` no Telegram"
authors:
  - first_name: Marcelo Ventura
    last_name: Freire
    email: mvf@usp.br
    country: br
    affiliation: "Escola de Artes, Ciências e Humanidades (EACHUSP)"
    url: ["https://t.me/rbrasiloficial", "https://github.com/mvf-each-usp"]
    corresponding: true
  - first_name: Leonardo Fernandes 
    last_name: Nascimento
    email: leofn3@gmail.com
    country: br
    affiliation: "Laboratório de Humanidades Digitais da UFBA (LABHDUFBA)"
    url: "https://github.com/leofn"
    corresponding: false
keywords: 
  - "comunidade"
  - "usuários"
  - "comunidade de usuários"
  - "telegram"
abstract: |
  ***PROVISÓRIO***: 
  Vamos convidar vocês para conhecerem a comunidade de usuários de R que usam 
  o grupo `R Brasil` no aplicativo de mensagens *Telegram*.  
  Compartilhamos experiências, perspectivas, notícias, dúvidas e discussões
  sobre o universo R e adjacências.
output: 
    latinr::latinr_article:
      keep_tex: false
      anonymise: true
params: 
  check_is_error: true
---

```{r submission-checks, echo=FALSE, warning=TRUE}
# Runs some basic checks in metadata. To disable, set check_is_error to FALSE
latinr::latinr_checks(rmarkdown::metadata, params$check_is_error)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Fundado em 5 de fevereiro de 2017, o grupo R Brasil no Telegram 
<https://t.me/rbrasiloficial> conta com 2.268 membro (em agosto de 2024)

